### ISSUE TITLE
Linux release link incorrect

### ISSUE THREAD

**Issue by CPSibo** [tmdh/laravel-kit#14]
In the readme, the link for the linux executable seems to be incorrect. It leads to a 404.

Current: `https://github.com/tmdh/laravel-kit/releases/download/v2.0.0/laravel-kit-2.0.0-x86_64.AppImage`
Actual: `https://github.com/tmdh/laravel-kit/releases/download/v2.0.0/Laravel-Kit-2.0.0.AppImage`

**Comment by tmdh** [comment]
Fixed. Now the links are correct.
