### ISSUE TITLE
Empty error message[MacOS]

### ISSUE THREAD

**Issue by DaaGER** [tmdh/laravel-kit#16]
Macbook Pro OS Catalina 10.15.7
"Open project" folder with Laravel
![image](https://user-images.githubusercontent.com/3992566/109974616-cd279380-7d0a-11eb-81db-eda5be27415d.png)

**Comment by tmdh** [comment]
What is the Laravel version of your project?

**Comment by DaaGER** [comment]
```
php artisan --version
Laravel Framework 8.29.0

```

**Comment by DaaGER** [comment]
Laravel Kit 2.0.1.
Fixed.
