### ISSUE TITLE
show project files

### ISSUE THREAD

**Issue by GlauberF** [tmdh/laravel-kit#20]
I uploaded a laravel project, but don't show me the files anywhere, so I can see or even edit.
I did not understand.

**Comment by tmdh** [comment]
Laravel Kit is not supposed to show you any files because it's not a code editor. You can just execute artisan commands. Go to **Artisan** section from the side bar to execute artisan commands.

**Comment by GlauberF** [comment]
since it has monaco, i think it would be an interesting feature.
It would be to show the files and when clicked, open in the monaco editor.

**Comment by tmdh** [comment]
For that, use a code editor. Laravel Kit is a simple admin panel for Laravel projects. I may add this in the future if it's relevant enough. Thanks.
