### ISSUE TITLE
No Icon on Ubuntu

### ISSUE THREAD

**Issue by travisfont-doctena** [tmdh/laravel-kit#21]
Empty icon shows on Ubuntu. Including, the AppImage doesn't allow to save to favorites.

**Comment by tmdh** [comment]
Can you check if it's fixed in v2.0.2?

**Comment by travisfont-doctena** [comment]
Still no fix.

**Comment by tmdh** [comment]
Icons works in my Gnome setup in Arch Linux. Please check if the issue is still there in 2.0.5 for Ubuntu.

**Comment by tmdh** [comment]
Fixed for deb release.
