### ISSUE TITLE
Add Laravel:Breeze to Artisan page.

### ISSUE THREAD

**Issue by oggiesutrisna** [tmdh/laravel-kit#22]
hi creator, this is exactly not a issue, i guess, i like your laravel kit software it makes me easier to make a project. But i have an support issue for your project, if you would next update your software, please add Laravel Breeze or more latest artisan update for your Laravel Kit software. Because i don't know, its more relevant when it uses, and also im lazy to use command prompt while im develop my app. So maybe next update you should add the Breeze to your laravel kit. 

Regards.

**Comment by tmdh** [comment]
If you want to execute Artisan commands related to breeze, they should be added automatically to your project. If they aren't there, go to **Project -> Reload project**.

**Comment by oggiesutrisna** [comment]
thanks for answering, i didn't see any breeze commands in artisan page on your kit while im open my project even im doing reload project. Maybe a little issue.

**Comment by tmdh** [comment]
`breeze:install` shows up fine. Did you mean any other commands?

![image](https://user-images.githubusercontent.com/18123729/112320701-5144b980-8cc0-11eb-9a5b-614f7cb8a090.png)
