### ISSUE TITLE
Is there any way to change the font type and size?

### ISSUE THREAD

**Issue by shiroamada** [tmdh/laravel-kit#23]
Is there any way to change the font type and size?

Or anyway zoom in  and zoom out?

**Comment by tmdh** [comment]
Zoom in and zoom out added in Laravel Kit v2.0.2.

**Comment by shiroamada** [comment]
> Zoom in and zoom out added in Laravel Kit v2.0.2.

I download from github, it will crash.

![image](https://user-images.githubusercontent.com/2062946/112782066-bdd40580-907e-11eb-8c17-e206f1ba24e2.png)


if I download from brew, it is still 2.0.1
![image](https://user-images.githubusercontent.com/2062946/112782651-1bb51d00-9080-11eb-94ae-3207a13e0ee2.png)

**Comment by tmdh** [comment]
Brew cask updated to 2.0.2.

**Comment by shiroamada** [comment]
Yes. Thanks!
![image](https://user-images.githubusercontent.com/2062946/112815120-9139e100-90b2-11eb-853d-5448deb328c7.png)

**Comment by shiroamada** [comment]
But unfortunately it still not able to open in my MacOS. same error from downloading from GitHub. Previously 2.0.1 also the same, but I able to open it when I use brew version.

![image](https://user-images.githubusercontent.com/2062946/112846153-4fbc2c80-90d8-11eb-939b-b2f374348900.png)
