### ISSUE TITLE
when Laragon run

### ISSUE THREAD

**Issue by azerioid** [tmdh/laravel-kit#29]
can't dedected php version  windows 10 64 bit

C:\laragon\bin\php\php-7.4

**Comment by evaleries** [comment]
You can manually configure the PHP path from the settings.

I also use PHP from Laragon. My directory: C:\laragon\bin\php\php-7.4.19-Win32-vc15-x64\php.exe

or you can try configure the PHP path to your environment variables and re-open Laravel Kit.
