### ISSUE TITLE
Tinker output not showing in v2.0.5 version

### ISSUE THREAD

**Issue by bakhtiyor-dev** [tmdh/laravel-kit#34]
Tinker output not showing in v2.0.5 version

**Comment by tmdh** [comment]
What is your operating system?

**Comment by Niush** [comment]
Same here. Windows 10
_Console error:_
![image](https://user-images.githubusercontent.com/16359077/150649243-aa696bf5-3d80-4114-99e1-4b56d1239b6c.png)

**Comment by tmdh** [comment]
Hi,
Can you please test by installing this one? My VM is running slow.

https://github.com/tmdh/hello-world/releases/download/2.0.6-rc1/Laravel-Kit-Setup-2.0.6.exe

**Comment by Niush** [comment]
Yes, that one is working properly. 🚀

**Comment by tmdh** [comment]
Fixed in v2.0.6 .
