### ISSUE TITLE
ErrorException     Writing to directory . is not allowed.

### ISSUE THREAD

**Issue by mahmoud-adel44** [tmdh/laravel-kit#35]
ErrorException 

  Writing to directory . is not allowed.

  at C:\Users\EGYPT_LAPTOP\.config\valet\Sites\ebid\vendor\psy\psysh\src\ConfigPaths.php:362
    358▕             @\mkdir($dir, 0700, true);
    359▕         }
    360▕ 
    361▕         if (!\is_dir($dir) || !\is_writable($dir)) {
  ➜ 362▕             \trigger_error(\sprintf('Writing to directory %s is not allowed.', $dir), \E_USER_NOTICE);
    363▕ 
    364▕             return false;
    365▕         }
    366▕

  1   C:\Users\EGYPT_LAPTOP\.config\valet\Sites\ebid\vendor\psy\psysh\src\ConfigPaths.php:362
      trigger_error("Writing to directory . is not allowed.")

  2   C:\Users\EGYPT_LAPTOP\.config\valet\Sites\ebid\vendor\psy\psysh\src\ConfigPaths.php:391
      Psy\ConfigPaths::ensureDir(".")

**Comment by tmdh** [comment]
What are the steps to reproduce the issue?

**Comment by mahmoud-adel44** [comment]
am trying to use tinker and i get this Exception

**Comment by benjamintemitope** [comment]
**Fixed!** If you are using Windows, run Laravel Kit as an administrator.

**Comment by tmdh** [comment]
It's no longer required to run the app as an administrator. This issue is fixed in v2.0.7.
