### ISSUE TITLE
PR for features acceptable?

### ISSUE THREAD

**Issue by damms005** [tmdh/laravel-kit#37]
I think it will be helpful to be able to save code snippets that can be re-useable.

I am open to contributing this feature. Is this allowed?

**Comment by luanfreitasdev** [comment]
I think so 
👉https://github.com/tmdh/laravel-kit/wiki#whats-nex

**Comment by tmdh** [comment]
Sure.

**Comment by damms005** [comment]
Thank you. You have also proven your point by accepting my first ever PR to this repo. I hope to do more for this awesome tool! Closing this for now.
