### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by mshoaibdev** [tmdh/laravel-kit#4]
Hey there,
First of all I'm excited to try out your package. Thanks for that!, If you could add Recent Projects feature in Project drop down, and what is the Open Editor command for sublime3.

**Comment by tmdh** [comment]
@muhammadshoaibwardak Thanks for your feature request.

> what is the Open Editor command for sublime3

`subl .` is the Open Editor command for Sublime Text 3. Make sure that the executable is available in your `PATH`.

**Comment by tmdh** [comment]
This feature is now available in v1.2.0.
