### ISSUE TITLE
“Laravel Kit.app” is damaged and can’t be opened. You should move it to the Bin.

### ISSUE THREAD

**Issue by hopkins385** [tmdh/laravel-kit#45]
Hi, 
on my Mac I get this error message after I ran yesterday brew upgrade. 

`“Laravel Kit.app” is damaged and can’t be opened. You should move it to the Bin.`

Laravel-Kit App 2.0.7
MacOs Monterey 12.6
Homebrew 3.6.4

**Comment by tmdh** [comment]
intel or m1 mac?

**Comment by hopkins385** [comment]
M1 Mac

**Comment by evaleries** [comment]
Can confirm this issue. For the workaround, you can install from DMG file on [GitHub release page.](https://github.com/tmdh/laravel-kit/releases/tag/v2.0.7)

<details>
<summary>Click me for the solution</summary>
You will see this pop up.
<img width="663" alt="image" src="https://user-images.githubusercontent.com/48923153/194779413-807b48da-69c9-4a5c-8698-7fcb6cecc0ef.png">

To address this issue, you can follow these steps
1. Click Cancel if you still see the pop-up.
1. Open Security & Privacy from System Preferences.
2. Click General Tab, down there you will see “Open Anyway” button. 
3. Click that button and click Open.

Running well on macOS Monterey 12.6 (M1)
<img width="867" alt="image" src="https://user-images.githubusercontent.com/48923153/194779536-8fa18b8e-e6e3-471b-a2c4-4a39fe39e89e.png">

Alternatively, you can run `xattr -cr /Applications/Laravel\ Kit.app` (untested)
</details>

**Comment by tmdh** [comment]
Well, I will probably remove the zip releases, and replace zips with dmgs in [hombrew-casks](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/laravel-kit.rb). Will that fix the issue? I don't have a Mac. (RFC)

**Comment by evaleries** [comment]
I'm not sure, but I'm willing to test.

**Comment by tmdh** [comment]
I have updated the Homebrew cask. Can you test the latest update with brew @evaleries ?

**Comment by tmdh** [comment]
I have updated the Homebrew cask. Can you please test the latest update with brew @evaleries ?

**Comment by evaleries** [comment]
Unfortunately, this solution doesn't work 😞 
![Image](https://user-images.githubusercontent.com/48923153/196417108-66bf9c61-4263-4e7e-913f-8b060ee5eaa5.png)

**Comment by tmdh** [comment]
Does running `xattr -d com.apple.quarantine /Applications/Laravel Kit.app` fixes it?

**Comment by evaleries** [comment]
> xattr -d com.apple.quarantine /Applications/Laravel Kit.app

Yes it works. `xattr -d com.apple.quarantine '/Applications/Laravel Kit.app'`

**Comment by tmdh** [comment]
Also, can you please check if `brew install laravel-kit --no-quarantine` works? If this works, I will add it to README.

**Comment by tmdh** [comment]
Thanks for testing. I updated the installation instructions in README.
