### ISSUE TITLE
Strange <whisper> tag when using Tinker

### ISSUE THREAD

**Issue by ouail** [tmdh/laravel-kit#47]
Hello,
I recently installed Laravel Kit for Mac (using brew & from release page)
I have a strange **<whisper></whisper>** tag, added for Tinker output.

<img width="1571" alt="Screen Shot 2022-12-25 at 14 57 49" src="https://user-images.githubusercontent.com/7101120/209470788-49a67a79-f483-415a-a62c-fc6bf6697108.png">

I think it's not related to my machine, as it doesn't occurs on some other projects.
It also occurs on a fresh laravel install, with no additional package install (see screenshot above)

<img width="1571" alt="Screen Shot 2022-12-25 at 14 57 57" src="https://user-images.githubusercontent.com/7101120/209470793-5da3d890-3c5f-45d6-aacc-d51568f6cb1d.png">

_composer.json_
`{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^8.0.2",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^9.19",
        "laravel/sanctum": "^3.0",
        "laravel/tinker": "^2.7"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
`
Did someone had this strange output ?

Thank you

**Comment by shtayeb** [comment]
@ouail Did you find anything on this issue?

**Comment by tmdh** [comment]
Fixed in Laravel Kit 2.0.8.
Consider donating.
https://ko-fi.com/tareque
