### ISSUE TITLE
New setting for command output height

### ISSUE THREAD

**Issue by damsfx** [tmdh/laravel-kit#48]
Does it make sense to you to have a new setting for the command output view to be maximize to the available window height?

Actual max height is very tiny on large screens due to `max-h-64` class.
https://github.com/tmdh/laravel-kit/blob/94c03d64c931ad767f4c90cbd5739b03554cf687/src/renderer/components/Command.vue#L29

**Comment by tmdh** [comment]
Would setting max-h-64 to min-h-64 help?

**Comment by damsfx** [comment]
> Would setting max-h-64 to min-h-64 help?

One solution would be to remove `max-h-64 overflow-y-auto`.  
The parent container is a column flexbox, the result of the command would take up the space it needs automatically.

But in this case, everything that comes before the result will no longer be fixed and will be in the scroll flow.

**Comment by tmdh** [comment]
Fixed by commit 6915166bc8df0863d215e960d0bcca7911e2e5a1 .
